package edunova;

public class E_2 {

	public static void main(String[] args) {
	
		// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

		int i;
		int F;
		int prvi=0,drugi=1;
		int sum=0;
		
		for(i=2;i<=4000000;i++) {
			
			F= prvi + drugi;
			
			if(F%2==0) {
				sum+=F;;
			}
			
			prvi = drugi;
			drugi = F;
			
		}
		
		System.out.println(sum);
		
	}

}
